// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC40iVPmoeZmVwxlu_vQZzni6_vXpnEsZc',
    appId: '1:401946278556:web:ab7659bea1ccd4178b0b59',
    messagingSenderId: '401946278556',
    projectId: 'dclub-32718',
    authDomain: 'dclub-32718.firebaseapp.com',
    databaseURL: 'https://dclub-32718-default-rtdb.firebaseio.com',
    storageBucket: 'dclub-32718.firebasestorage.app',
    measurementId: 'G-83B6H155CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0bGypT2DddGl7PZey2V3SmJebf3gund0',
    appId: '1:401946278556:android:efb673f718ddd2b88b0b59',
    messagingSenderId: '401946278556',
    projectId: 'dclub-32718',
    databaseURL: 'https://dclub-32718-default-rtdb.firebaseio.com',
    storageBucket: 'dclub-32718.firebasestorage.app',
  );
}
